# Generated by Django 4.2.30 on 2026-08-07 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_class', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('original_image_b64', models.TextField()),
                ('gradcam_b64', models.TextField(blank=True, default='')),
                ('shap_b64', models.TextField(blank=True, default='')),
                ('integrated_gradients_b64', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
