/**
 * Single source of the non-clinical disclaimer text.
 * variant "banner"  — full-width caution-tinted strip with a short lead.
 * variant "inline"  — the full paragraph, used inside the exported PDF section.
 */
const FULL_TEXT =
  "This report was generated by NeuroScan-XAI for academic, research and " +
  "educational use only. It is not a medical device and its output must not " +
  "be used for clinical diagnosis of any kind. The XAI outputs (Grad-CAM, " +
  "LRP, SHAP) explain the behaviour of the model — they are not tumour " +
  "segmentations and carry no diagnostic validity.";

export default function DisclaimerBanner({ variant = "banner" }) {
  if (variant === "inline") {
    return <p className="disclaimer-banner disclaimer-banner--inline">{FULL_TEXT}</p>;
  }

  return (
    <div className="disclaimer-banner disclaimer-banner--banner" role="note">
      <strong className="disclaimer-banner__lead">
        Research demonstration — not a medical device.
      </strong>
      <span className="disclaimer-banner__text">{FULL_TEXT}</span>
    </div>
  );
}
